version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: prmp-postgres
    environment:
      POSTGRES_USER: prmp
      POSTGRES_PASSWORD: prmp
      POSTGRES_DB: prmp_registry
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prmp"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: prmp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  registry:
    build: .
    container_name: prmp-registry
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 3000
      HOST: 0.0.0.0
      DATABASE_URL: postgresql://prmp:prmp@postgres:5432/prmp_registry
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev-secret-change-in-production
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    command: npm run dev

volumes:
  postgres_data:
  redis_data:
