version: '3.8'

services:
  # Shared PostgreSQL database for all services
  postgres:
    image: postgres:15-alpine
    container_name: prpm-postgres
    environment:
      POSTGRES_USER: prpm
      POSTGRES_PASSWORD: prpm
      POSTGRES_DB: prpm
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prpm"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Shared Redis for all services
  redis:
    image: redis:7-alpine
    container_name: prpm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Shared MinIO for all services
  minio:
    image: minio/minio:latest
    container_name: prpm-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  minio_data:
