name: 'Karen Code Review'
description: 'Get a brutally honest, cynical code review from Karen - no BS, just reality checks'
author: 'PRPM'
branding:
  icon: 'alert-circle'
  color: 'yellow'

inputs:
  anthropic_api_key:
    description: 'Anthropic API key for Claude (optional if openai_api_key provided)'
    required: false
  openai_api_key:
    description: 'OpenAI API key (optional if anthropic_api_key provided)'
    required: false
  ai_provider:
    description: 'AI provider to use: anthropic or openai (auto-detected if not specified)'
    required: false
    default: 'auto'
  github_token:
    description: 'GitHub token for commenting on PRs'
    required: false
    default: ${{ github.token }}
  mode:
    description: 'Review mode: full, pr, or update'
    required: false
    default: 'full'
  post_comment:
    description: 'Post Karen review as PR comment'
    required: false
    default: 'true'
  generate_badge:
    description: 'Generate Karen score badge'
    required: false
    default: 'true'
  min_score:
    description: 'Minimum Karen score to pass (0-100)'
    required: false
    default: '0'

outputs:
  karen_score:
    description: 'Karen score (0-100)'
  karen_grade:
    description: 'Karen grade (Delete this and start over, Needs intervention, etc.)'
  review_path:
    description: 'Path to generated review markdown'
  badge_path:
    description: 'Path to generated badge SVG'

runs:
  using: 'node20'
  main: 'dist/index.js'
