# Karen Configuration
# Customize how Karen reviews your repository

# Scoring weights (must sum to 1.0)
weights:
  bullshitFactor: 0.25      # Penalize over-engineering
  actuallyWorks: 0.25        # Does it actually work?
  codeQualityReality: 0.20   # Is it maintainable?
  completionHonesty: 0.15    # TODOs vs done
  practicalValue: 0.15       # Does anyone need this?

# Directories and files to ignore
ignore:
  - node_modules
  - dist
  - build
  - coverage
  - .git
  - vendor
  - "*.lock"
  - package-lock.json
  - yarn.lock
  - pnpm-lock.yaml

# Focus areas for review (optional)
# If specified, Karen will prioritize these directories
focus:
  - src
  - lib
  - packages

# Strictness level (1-10, default: 7)
# Higher = more brutal, Lower = more forgiving
strictness: 7

# Enable specific checks
checks:
  overEngineering: true      # Flag unnecessary complexity
  missingTests: true         # Flag lack of tests
  incompleteTodos: true      # Flag TODOs and FIXMEs
  deadCode: true             # Flag unused code
  unnecessaryDeps: true      # Flag unused dependencies

# Thresholds
thresholds:
  minScore: 50               # Minimum acceptable score
  todoLimit: 20              # Max TODOs before penalty
  complexityLimit: 15        # Max cyclomatic complexity
