name: CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  # Registry Service Tests
  registry-tests:
    name: Registry Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: prpm
          POSTGRES_PASSWORD: prpm
          POSTGRES_DB: prpm_registry
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build types package (required dependency)
        run: npm run build --workspace=@pr-pm/types

      - name: Start MinIO
        run: |
          docker run -d \
            --name minio \
            -p 9000:9000 -p 9001:9001 \
            -e MINIO_ROOT_USER=minioadmin \
            -e MINIO_ROOT_PASSWORD=minioadmin \
            minio/minio:latest server /data --console-address ":9001"

      - name: Wait for MinIO
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:9000/minio/health/live 2>/dev/null; do echo "Waiting for MinIO..."; sleep 2; done'
          echo "✅ MinIO is ready"

      - name: Type check
        working-directory: ./packages/registry
        run: npx tsc --noEmit

      - name: Build
        working-directory: ./packages/registry
        run: npm run build

      - name: Run tests
        working-directory: ./packages/registry
        run: npm test -- --run
        env:
          DATABASE_URL: postgresql://prpm:prpm@localhost:5432/prpm_registry
          REDIS_URL: redis://localhost:6379
          S3_ENDPOINT: http://localhost:9000
          S3_ACCESS_KEY: minioadmin
          S3_SECRET_KEY: minioadmin
          S3_BUCKET: prpm-packages
          JWT_SECRET: test-secret-key-for-ci
          NODE_ENV: test

  # CLI Tests
  cli-tests:
    name: CLI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build types package (required dependency)
        run: npm run build --workspace=@pr-pm/types

      - name: Build registry-client
        run: npm run build --workspace=@pr-pm/registry-client

      - name: Type check
        working-directory: ./packages/cli
        run: npx tsc --noEmit

      - name: Run tests
        working-directory: ./packages/cli
        run: npm test

      - name: Build
        working-directory: ./packages/cli
        run: npm run build

  # Registry Client Tests
  registry-client-tests:
    name: Registry Client Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build types package (required dependency)
        run: npm run build --workspace=@pr-pm/types

      - name: Run tests
        working-directory: ./packages/registry-client
        run: npm test

      - name: Type check
        working-directory: ./packages/registry-client
        run: npx tsc --noEmit

      - name: Build
        working-directory: ./packages/registry-client
        run: npm run build

  # Security Checks
  security:
    name: Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run npm audit
        run: |
          cd packages/registry && npm audit --audit-level=high || echo "Vulnerabilities found"
          cd ../packages/cli && npm audit --audit-level=high || echo "Vulnerabilities found"
          cd ../packages/registry-client && npm audit --audit-level=high || echo "Vulnerabilities found"

  # Types Package Tests
  types-tests:
    name: Types Package Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Type check
        working-directory: ./packages/types
        run: npx tsc --noEmit

      - name: Build
        working-directory: ./packages/types
        run: npm run build

  # Webapp Tests
  webapp-tests:
    name: Webapp Build & Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install root dependencies
        run: npm ci

      - name: Build types package (required dependency)
        run: npm run build --workspace=@pr-pm/types

      - name: Install webapp dependencies
        working-directory: ./packages/webapp
        run: npm ci

      - name: Type check
        working-directory: ./packages/webapp
        run: npx tsc --noEmit

      - name: Lint
        working-directory: ./packages/webapp
        run: npm run lint

      - name: Create mock SSG data files
        run: |
          # Create directory and mock data with at least one entry
          # (Next.js requires generateStaticParams to return non-empty array with output: export)
          mkdir -p packages/webapp/public/seo-data

          # Mock package data
          echo '[{"name":"@prpm/test-package","description":"Test package for CI builds","format":"cursor","subtype":"rules","total_downloads":0,"weekly_downloads":0}]' > packages/webapp/public/seo-data/packages.json

          # Mock collection data
          echo '[{"name_slug":"test-collection","description":"Test collection for CI builds","package_count":0,"downloads":0,"stars":0}]' > packages/webapp/public/seo-data/collections.json

          echo "✓ Mock SSG data files created with test entries"

      - name: Build
        working-directory: ./packages/webapp
        run: npm run build

  # Webapp E2E Tests with Playwright
  webapp-e2e-tests:
    name: Webapp E2E Tests (Playwright)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install root dependencies
        run: npm ci

      - name: Build types package (required dependency)
        run: npm run build --workspace=@pr-pm/types

      - name: Install webapp dependencies
        working-directory: ./packages/webapp
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./packages/webapp
        run: npx playwright install --with-deps chromium

      - name: Start dev server in background
        working-directory: ./packages/webapp
        run: |
          npm run dev &
          echo $! > .dev-server.pid
          # Wait for dev server to be ready
          timeout 60 bash -c 'until curl -s http://localhost:5173 > /dev/null; do echo "Waiting for dev server..."; sleep 2; done'
          echo "✅ Dev server is ready"

      - name: Run Playwright tests
        working-directory: ./packages/webapp
        run: npx playwright test smoke.spec.ts --project=chromium
        env:
          CI: true

      - name: Stop dev server
        if: always()
        working-directory: ./packages/webapp
        run: |
          if [ -f .dev-server.pid ]; then
            kill $(cat .dev-server.pid) || true
            rm .dev-server.pid
          fi

      - name: Upload Playwright report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: packages/webapp/playwright-report/
          retention-days: 7

      - name: Upload test results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: packages/webapp/test-results/
          retention-days: 7

  # All checks summary
  all-checks:
    name: All Checks
    runs-on: ubuntu-latest
    needs: [registry-tests, cli-tests, registry-client-tests, types-tests, webapp-tests, webapp-e2e-tests, security]
    if: always()

    steps:
      - name: Summary
        run: echo "✅ CI checks completed"
