name: Infrastructure Preview

on:
  pull_request:
    paths:
      - 'packages/infra/**'
      - '.github/workflows/infra-*.yml'
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  AWS_REGION: us-west-2

jobs:
  preview:
    name: Pulumi Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: [prod]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Pulumi
        uses: pulumi/actions@v5

      - name: Verify Beanstalk configuration
        working-directory: packages/infra
        run: |
          if ! grep -q "Elastic Beanstalk" index.ts; then
            echo "Error: index.ts is not using Beanstalk configuration"
            exit 1
          fi
          echo "✅ Using Beanstalk configuration"

      - name: Configure Stack
        working-directory: packages/infra
        run: |
          STACK="${{ matrix.stack }}"
          pulumi stack select $STACK || pulumi stack init $STACK

          # AWS region
          pulumi config set aws:region ${{ env.AWS_REGION }}

          # Database credentials
          pulumi config set db:username prpm
          pulumi config set --secret db:password "${{ secrets.DB_PASSWORD }}"

          # GitHub OAuth
          pulumi config set --secret github:clientId "${{ secrets.GITHUB_CLIENT_ID }}"
          pulumi config set --secret github:clientSecret "${{ secrets.GITHUB_CLIENT_SECRET }}"

          # Beanstalk configuration
          pulumi config set app:instanceType t3.micro
          pulumi config set app:minSize 1
          pulumi config set app:maxSize 2

          # Domain configuration
          if [ "$STACK" = "prod" ]; then
            pulumi config set app:domainName registry.prpm.dev
          fi

      - name: Pulumi Preview
        working-directory: packages/infra
        run: |
          pulumi preview --diff --non-interactive
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
